Mike/add filter for library
OlivierJM/sparked-next pull request #162
Opened 2024-05-28 20:15 UTC by mikemtdev

### This PR adds: 
- Grades
- Subjects
- Units
- Topics
- Categories

<img width="1440" alt="image" src="https://github.com/SparkEdUAB/sparked-next/assets/45319708/3b1e066b-2754-4805-ba50-2b8a1ac3cd68">

#### Showing no Items for filter
<img width="1440" alt="image" src="https://github.com/SparkEdUAB/sparked-next/assets/45319708/b72e4cb8-f45d-4ad5-acd5-77ad6e0c2ec5">

#### Showing items for filter
<img width="1440" alt="image" src="https://github.com/SparkEdUAB/sparked-next/assets/45319708/fd9ad264-9729-4617-b20a-7bfbf8ab2960">

2024-05-30 04:32 UTC, mikemtdev commented
> So eventually we are getting rid of courses, we will have the following filters
> 
>     * Grades
> 
>     * Subjects
> 
>     * Units
> 
>     * Topics
> 
> 
> The tags at the top will just be categories of the media content.
> 
> You can refer to the section here https://www.alemhulu.com
> 
> @brianmuks this means we should be able to query media contents Just by Grade, or by Subjects or by Units or Topics or Category in case there's need for BE support.

So this means there will be two places where subjects will appear?

2024-05-30 17:40 UTC, mikemtdev commented on src/app/api/media-content/index.ts
> +    console.debug('query', query);
Thanks will remove. 
I do think it would be best adding a rule. 
Just in case.

2024-05-31 11:01 UTC, brianmuks commented
> So eventually we are getting rid of courses, we will have the following filters
> 
> * Grades
> * Subjects
> * Units
> * Topics
> 
> The tags at the top will just be categories of the media content.
> 
> You can refer to the section here https://www.alemhulu.com
> 
> @brianmuks this means we should be able to query media contents Just by Grade, or by Subjects or by Units or Topics or Category in case there's need for BE support.

I will look into this.

2024-05-31 11:14 UTC, brianmuks requested changes

2024-05-31 11:14 UTC, brianmuks commented on src/app/api/media-content/index.ts
> +    grade_id: z.string().optional(),
@mikemtdev  I noticed you might be working on the backend for too.

While I'm happy to offer assistance if needed, I wanted to highlight the importance of maintaining clear documentation for future updates.

Unsolicited changes to the backend code can sometimes make it difficult to keep the frontend and backend in sync.

To ensure smooth collaboration and long-term maintainability, would you be open to discussing any planned backend changes before implementation? This way, we can keep the documentation up-to-date and avoid potential issues down the line.

Let me know your thoughts, and I'm happy to chat further!

2024-05-31 14:54 UTC, brianmuks commented on src/app/api/media-content/index.ts
> +    grade_id: z.string().optional(),
@OlivierJM I am currently documenting end points in postman. @mikemtdev What do you need from the backend with regards to this `PR` ?

2024-06-01 21:00 UTC, mikemtdev commented
> @mikemtdev let us know if you are blocked on this or if there is anything we can help with. 

No just need to remove backend files that I touched/added. 
Will make changes

2024-06-02 17:22 UTC, mikemtdev commented
> @mikemtdev as part of this PR, can we a way to mark a filter that is currently selected(some active state like on dashboard), e.g: a user should know that they selected Grade 10, some params may help `?grade=10&subject=chemistry&topic=something` This way it is easier also to persist urls and even easier to come back to it.

I added something similar. This is via a hook called useSearchQuery. 
it will append to the URL string 
<img width="1433" alt="image" src="https://github.com/SparkEdUAB/sparked-next/assets/45319708/1c435cb9-273a-461e-8fad-f20c71aef3e2">

When you add a topic to the grade filter
<img width="1440" alt="image" src="https://github.com/SparkEdUAB/sparked-next/assets/45319708/a9bd9cd6-5055-4ca9-94fd-6815d4c1287b">

2024-06-02 19:01 UTC, mikemtdev commented
> > I added something similar. This is via a hook called useSearchQuery.
> 
> Yes this is good, do we get active items that were selected or this will be done in a separate issue, I would love to merge this sooner.

Yes, it shows. 
<img width="1440" alt="image" src="https://github.com/SparkEdUAB/sparked-next/assets/45319708/12a4fcac-e8c5-4c2c-a52a-c5e9c8ead140">

2024-06-02 19:15 UTC, merged