configure typescript
OlivierJM/sparked-next pull request #3
Opened 2023-08-17 17:33 UTC by brianmuks

2023-08-17 19:52 UTC, OlivierJM requested changes
Let's also keep the package-lock.json for package consistency.

2023-08-17 19:52 UTC, OlivierJM commented on package.json
> +  "name": "next-typescript-example",
Better to keep the name as is.

2023-08-18 07:23 UTC, brianmuks commented on package.json
> +  "name": "next-typescript-example",
I didn’t notice. Sorry I will revert

2023-08-18 07:33 UTC, brianmuks commented
@OlivierJM . I have made the requested changes.

2023-08-18 07:34 UTC, OlivierJM approved these changes

2023-08-18 15:07 UTC, merged